# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-06-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('full_url', models.CharField(max_length=255, unique=True)),
                ('short_url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_url_mapping',
            },
        ),
    ]
